import { afterEach, describe, expect, it, vi } from "vitest";
import { LocalRuntimeClient } from "./local-runtime-client";
import {
  normalizeCodexOptions,
  toNativeBridgeRequest,
  type LocalRuntimeExtensionResponse,
} from "./native-bridge-contract";

describe("LocalRuntimeClient", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("returns unavailable when the extension runtime is missing", async () => {
    vi.stubGlobal("chrome", undefined);

    const status = await new LocalRuntimeClient().isAvailable();

    expect(status.available).toBe(false);
    expect(status.mode).toBe("local-chatgpt-codex");
    expect(status.reason).toContain("Chrome extension runtime");
  });

  it("reads native bridge status through the background service worker", async () => {
    stubChromeMessage({
      ok: true,
      data: {
        available: true,
        mode: "local-chatgpt-codex",
        reason: "Native bridge ready",
      },
    });

    const status = await new LocalRuntimeClient().isAvailable();

    expect(status.available).toBe(true);
    expect(status.reason).toBe("Native bridge ready");
  });

  it("generates an answer through the native bridge route", async () => {
    const sendMessage = stubChromeMessage({
      ok: true,
      data: {
        answer: "Generated by local Codex",
        draftSummary: {
          conclusion: "Review complete",
          tags: ["assistant"],
          scope: "ARCH-1",
        },
      },
    });

    const output = await new LocalRuntimeClient().generateAnswer({
      question: "Check this task",
      taskContext: {
        taskId: "task-1",
        projectId: "project-1",
        title: "Review task",
        description: "",
        status: "open",
        issueId: "ARCH-1",
        projectName: "Architect",
      },
      evidence: [],
    });

    expect(sendMessage).toHaveBeenCalledWith(
      expect.objectContaining({ type: "architect:local-runtime-generate" }),
      expect.any(Function),
    );
    expect(output.answer).toBe("Generated by local Codex");
  });

  it("normalizes Codex options and maps usage summary to the native request contract", () => {
    const codexOptions = normalizeCodexOptions({
      model: "gpt-5-codex",
      reasoningEffort: "medium",
      serviceTier: "priority",
      sandboxMode: "read-only",
      configPath: "C:\\Users\\secret\\.codex\\config.toml",
      path: "D:\\workspace",
      env: { OPENAI_API_KEY: "secret" },
      stderr: "raw log",
    });

    expect(codexOptions).toEqual({
      reasoningEffort: "medium",
      serviceTier: "priority",
      sandboxMode: "read-only",
    });
    expect(
      toNativeBridgeRequest(
        {
          type: "architect:local-runtime-usage-summary",
          codexOptions,
        },
        "usage-request",
      ),
    ).toEqual({
      type: "usageSummary",
      requestId: "usage-request",
      codexOptions,
    });

    const input = {
      question: "Check this task",
      taskContext: {
        taskId: "task-1",
        projectId: "project-1",
        title: "Review task",
        description: "",
        status: "open",
        issueId: "ARCH-1",
        projectName: "Architect",
      },
      evidence: [],
      legalEvidence: [],
      projectContextChunks: [
        {
          chunkId: "chunk-1",
          sourceDocumentTitle: "회의록",
          normalizedText: "현장 조건은 북측 도로와 1.2m 단차가 있다.",
          sourceQuote: "북측 도로와 1.2m 단차",
          location: { locationType: "line_range", lineStart: 3, lineEnd: 4 },
          contextType: "project_material",
          chunkQualityScore: 0.91,
          injectionRisk: "none",
          score: 0.83,
        },
      ],
      projectContextTrace: {
        status: "chunks_found" as const,
        fallbackMode: "none" as const,
        includedChunkIds: ["chunk-1"],
      },
      evidenceReadinessWarnings: [
        { code: "VERIFIED_LEGAL_CHANGE_WARNING", message: "법령 변경 감지 결과를 확인하세요." },
      ],
    };
    expect(
      toNativeBridgeRequest(
        {
          type: "architect:local-runtime-generate",
          input,
          codexOptions,
        },
        "generate-request",
      ),
    ).toEqual({
      type: "generate",
      requestId: "generate-request",
      payload: input,
      codexOptions,
    });
  });
});

function stubChromeMessage<T>(response: LocalRuntimeExtensionResponse<T>) {
  const sendMessage = vi.fn((_: unknown, callback: (value: LocalRuntimeExtensionResponse<T>) => void) => {
    callback(response);
  });
  vi.stubGlobal("chrome", {
    runtime: {
      lastError: undefined,
      sendMessage,
    },
  });
  return sendMessage;
}
