import { afterEach, describe, expect, it, vi } from "vitest";
import { LocalRuntimeClient } from "./local-runtime-client";
import type { LocalRuntimeExtensionResponse } from "./native-bridge-contract";

describe("LocalRuntimeClient", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("returns unavailable when the extension runtime is missing", async () => {
    vi.stubGlobal("chrome", undefined);

    const status = await new LocalRuntimeClient().isAvailable();

    expect(status.available).toBe(false);
    expect(status.mode).toBe("local-chatgpt-codex");
    expect(status.reason).toContain("Chrome extension runtime");
  });

  it("reads native bridge status through the background service worker", async () => {
    stubChromeMessage({
      ok: true,
      data: {
        available: true,
        mode: "local-chatgpt-codex",
        reason: "Native bridge ready",
      },
    });

    const status = await new LocalRuntimeClient().isAvailable();

    expect(status.available).toBe(true);
    expect(status.reason).toBe("Native bridge ready");
  });

  it("generates an answer through the native bridge route", async () => {
    const sendMessage = stubChromeMessage({
      ok: true,
      data: {
        answer: "Generated by local Codex",
        draftSummary: {
          conclusion: "Review complete",
          tags: ["assistant"],
          scope: "ARCH-1",
        },
      },
    });

    const output = await new LocalRuntimeClient().generateAnswer({
      question: "Check this task",
      taskContext: {
        taskId: "task-1",
        projectId: "project-1",
        title: "Review task",
        description: "",
        status: "open",
        issueId: "ARCH-1",
        projectName: "Architect",
      },
      evidence: [],
    });

    expect(sendMessage).toHaveBeenCalledWith(
      expect.objectContaining({ type: "architect:local-runtime-generate" }),
      expect.any(Function),
    );
    expect(output.answer).toBe("Generated by local Codex");
  });
});

function stubChromeMessage<T>(response: LocalRuntimeExtensionResponse<T>) {
  const sendMessage = vi.fn((_: unknown, callback: (value: LocalRuntimeExtensionResponse<T>) => void) => {
    callback(response);
  });
  vi.stubGlobal("chrome", {
    runtime: {
      lastError: undefined,
      sendMessage,
    },
  });
  return sendMessage;
}
